# ROS 2
export ROS_DISTRO=jazzy

source /opt/ros/$ROS_DISTRO/setup.bash

if [ -f ~/ros_ws/install/setup.bash ]; then
    source ~/ros_ws/install/setup.bash
fi

export ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}

#Bash completion
if [ -f /usr/share/bash-completion/bash-completion ]; then
    source /usr/share/bash-completion/bash-completion
fi

export PS1="(ROS_ID=\$ROS_DOMAIN_ID) \u@\h:\w\$"

# Alias

alias reload="source ~/.bashrc"
alias killros="pkill -f ros2"
# ROS 2
export ROS_DISTRO=jazzy

source /opt/ros/$ROS_DISTRO/setup.bash

if [ -f ~/ros_ws/install/setup.bash ]; then
    source ~/ros_ws/install/setup.bash
fi

export ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}

export PS1="(ROS_ID=\$ROS_DOMAIN_ID) \u@\h:\w\$"

# Alias
alias reload="source ~/.bashrc"
alias killros="pkill -f ros2"
